# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='topic',
            new_name='top_name',
        ),
    ]
